export default {
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILURE: 'GET_USER_DATA_FAILURE',
  AUTHORIZE_SUCCESS: 'AUTHORIZE_SUCCESS',
  AUTHORIZE_FAILURE: 'AUTHORIZE_FAILURE',
};
